In [44]:
import tensorflow as tf
import constants
from transfer_CNN import TransferCNN
from data_generator import DataGenerator


In [45]:
model = tf.keras.models.load_model("model_fold_0")

In [3]:
from prepare_dataset import split_train_test

In [5]:
folds_list = split_train_test(constants.PATCH_OUTPUT_DIRECTORY, 5)

Fold 0
Train:
Large_Tumor_Cells: 12016
Small_Tumor_Cells: 12882
Test:
Large_Tumor_Cells: 3535
Small_Tumor_Cells: 1115
_______________________________________
Fold 1
Train:
Large_Tumor_Cells: 12995
Small_Tumor_Cells: 11741
Test:
Large_Tumor_Cells: 2556
Small_Tumor_Cells: 2256
_______________________________________
Fold 2
Train:
Large_Tumor_Cells: 15485
Small_Tumor_Cells: 6885
Test:
Large_Tumor_Cells: 66
Small_Tumor_Cells: 7112
_______________________________________
Fold 3
Train:
Large_Tumor_Cells: 6695
Small_Tumor_Cells: 13493
Test:
Large_Tumor_Cells: 8856
Small_Tumor_Cells: 504
_______________________________________
Fold 4
Train:
Large_Tumor_Cells: 15013
Small_Tumor_Cells: 10987
Test:
Large_Tumor_Cells: 538
Small_Tumor_Cells: 3010
_______________________________________


In [6]:
from prepare_dataset import get_dataset_for_fold

In [46]:
data, labels, class_to_label = get_dataset_for_fold(constants.PATCH_OUTPUT_DIRECTORY, folds_list, 1)

In [47]:
test_gen = DataGenerator(data['test'], labels['test'])

In [48]:
imgs = test_gen.__getitem__(4)[0]

In [49]:
imgs[0]

array([[[0.96875   , 0.58203125, 0.8046875 ],
        [0.97265625, 0.5859375 , 0.80859375],
        [0.97265625, 0.5859375 , 0.80859375],
        ...,
        [0.55859375, 0.48046875, 0.7578125 ],
        [0.53515625, 0.4765625 , 0.74609375],
        [0.51953125, 0.46875   , 0.73828125]],

       [[0.96484375, 0.58203125, 0.8046875 ],
        [0.96875   , 0.58203125, 0.8046875 ],
        [0.97265625, 0.5859375 , 0.80859375],
        ...,
        [0.5234375 , 0.45703125, 0.734375  ],
        [0.51171875, 0.44921875, 0.7265625 ],
        [0.4921875 , 0.44140625, 0.7109375 ]],

       [[0.96484375, 0.58203125, 0.8046875 ],
        [0.96484375, 0.58203125, 0.8046875 ],
        [0.96484375, 0.58203125, 0.8046875 ],
        ...,
        [0.51171875, 0.44921875, 0.734375  ],
        [0.48828125, 0.4375    , 0.71875   ],
        [0.47265625, 0.42578125, 0.70703125]],

       ...,

       [[0.9609375 , 0.578125  , 0.80078125],
        [0.95703125, 0.57421875, 0.796875  ],
        [0.953125  , 0

In [57]:
labels = test_gen.__getitem__(4)[1]
labels

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0])

In [53]:
pred = model.predict(imgs)

In [54]:
pred

array([[0.73730314],
       [0.70065856],
       [0.6878252 ],
       [0.73113394],
       [0.730013  ],
       [0.7035779 ],
       [0.6673736 ],
       [0.7421068 ],
       [0.6987495 ],
       [0.685504  ],
       [0.69261754],
       [0.70210636],
       [0.7016282 ],
       [0.6860353 ],
       [0.6670346 ],
       [0.6668663 ],
       [0.6666185 ],
       [0.7058162 ],
       [0.66698956],
       [0.68265355],
       [0.66751206],
       [0.6667921 ],
       [0.69508255],
       [0.6689125 ],
       [0.67468995],
       [0.6676301 ],
       [0.67307335],
       [0.6673104 ],
       [0.71053946],
       [0.66754085],
       [0.6671934 ],
       [0.666934  ]], dtype=float32)

In [33]:
train_gen = DataGenerator(data['train'], labels['train'])

In [43]:
train_gen.__getitem__(5)[1]

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1])

In [68]:
from tensorflow.keras.losses import binary_crossentropy
import numpy as np

In [71]:
labels = labels.reshape(-1, 1)
labels.astype(np.float32)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [62]:
pred

array([[0.73730314],
       [0.70065856],
       [0.6878252 ],
       [0.73113394],
       [0.730013  ],
       [0.7035779 ],
       [0.6673736 ],
       [0.7421068 ],
       [0.6987495 ],
       [0.685504  ],
       [0.69261754],
       [0.70210636],
       [0.7016282 ],
       [0.6860353 ],
       [0.6670346 ],
       [0.6668663 ],
       [0.6666185 ],
       [0.7058162 ],
       [0.66698956],
       [0.68265355],
       [0.66751206],
       [0.6667921 ],
       [0.69508255],
       [0.6689125 ],
       [0.67468995],
       [0.6676301 ],
       [0.67307335],
       [0.6673104 ],
       [0.71053946],
       [0.66754085],
       [0.6671934 ],
       [0.666934  ]], dtype=float32)

In [88]:
t = binary_crossentropy(labels.astype(np.float32).reshape(-1), pred.reshape(-1), True)

In [82]:
import tensorflow.keras.backend

In [90]:
tf.keras.backend.get_value(t)

0.87900364

In [84]:
class_to_label

{'large_tumor_cells': 0, 'small_tumor_cells': 1}